Repository JosephusPaye/Keen-UI, pull requests merged in 2019-01, with the labels that each got.

#397 Update UiSelect.vue
  docs-src/pages/UiSelect.vue
Labels: enhancement, intend to add

#372 fix IE11 Issue with multiline textbox (textarea)
  src/UiTextbox.vue
Labels: accepted, bug

#367 Fix overlapping of input auto filled value and label
  src/UiTextbox.vue
Labels: accepted, bug

#275 Add a focus() method to UiTextbox
  src/UiTextbox.vue
Labels: enhancement, intend to implement

#368 UiSlider with minValue and maxValue parameters
  docs-src/pages/UiSlider.vue
  src/UiSlider.vue
Labels: enhancement

#294 A proposal for post-filter sorting API
  src/UiAutocomplete.vue
Labels: enhancement, intend to implement

#305 allow string and can set "0"
  src/UiSlider.vue
Labels: bug, intend to implement

#425 Allow UIDatepicker 'value' prop accept ISO 8601 string.
  src/UiDatepicker.vue
Labels: enhancement, intend to add
